- name: "PLAY 1 - Generate Zscaler Tunnel Configuration"
  hosts: localhost
  connection: local
 
  tasks:
    - name: Geting File Names
######## send command find to ansible host to find all the yaml files#############
      shell: "find *.yaml"
######## send freee form od the chdir command, the args help to send the drectory to serach the file ##########
      args:
        chdir: "./host_vars/"
######## register the opuput of the command, and convert the file names in var list########################
      register: files
  
    - name: "Reading Files"
############ creation of the files with the name variables ############
      include_tasks: process.yaml
############ the stdout_lines is the output of the command regiter and get all the variables########
############ loop permit to perfomr the tastk on procees file one by one ####################     
      loop: "{{ files.stdout_lines }}"
